import {
  AdminDashboardSummary,
  AdminHealthResponse,
  EvaluationDetail,
  EvaluationListItem,
  ImportRunDetail,
  ImportRunListItem,
  MemberListItem,
  PageResponse,
  PlaceDetail,
  PlaceListItem,
  ProviderStatus,
  SyncJob,
  SyncRun,
} from "./contracts";

export const DEMO_HEALTH: AdminHealthResponse = {
  status: "ok",
  database: "connected",
  publicApi: "connected",
  timestamp: "2026-08-22T03:00:00.000Z",
};

export const DEMO_SUMMARY: AdminDashboardSummary = {
  places: {
    total: 1250,
    withoutLocation: 12,
    kto: 980,
    naver: 270,
    kakao: 0,
    mock: 0,
    other: 0,
    verifiedPriceRecords: 1,
    unverifiedPriceRecords: 0,
    bySource: { "kto-tour-jpn": 980, "naver-local": 270 },
  },
  tourismMetrics: {
    total: 4500,
    linkedPlaces: 820,
    latestReferencePeriod: "2026-07",
  },
  imports: {
    latestCompletedAt: "2026-08-20T14:30:00.000Z",
    latestStatus: "completed",
    recentRejectCount: 5,
  },
  evaluations: {
    total: 38,
    latestGeneratedAt: "2026-08-21T09:15:00.000Z",
  },
  members: {
    total: 24,
    active: 23,
    savedTrips: 31,
    latestRegisteredAt: "2026-08-21T12:00:00.000Z",
  },
};

export const DEMO_PROVIDERS: ProviderStatus = {
  place: "mock",
  kto: "live",
  tourismDataLab: "live",
  crowd: "mock",
  llm: "mock",
  routing: "live",
  accessibility: "unavailable",
  placeSource: "kakao-local",
  crowdSource: "seoul-open-data",
  checkedAt: "2026-08-22T03:00:00.000Z",
  publicApiStatus: "connected",
};

export const DEMO_PLACES: PageResponse<PlaceListItem> = {
  items: [
    {
      id: "demo-p-1",
      name: "경복궁",
      source: "kto",
      sourcePlaceId: "kto-1001",
      category: "관광지",
      address: "서울특별시 종로구 사직로 161",
      roadAddress: "서울특별시 종로구 사직로 161",
      latitude: 37.579617,
      longitude: 126.977041,
      coordinateStatus: "present",
      estimatedCostKrw: 3000,
      priceEvidenceSource: "manual",
      priceEvidenceVerificationStatus: "verified",
      tourismMetricCount: 6,
      latestTourismPeriod: "2026-07",
      createdAt: "2026-08-01T00:00:00.000Z",
      updatedAt: "2026-08-20T00:00:00.000Z",
    },
    {
      id: "demo-p-2",
      name: "북촌한옥마을",
      source: "kto",
      sourcePlaceId: "kto-1002",
      category: "관광지",
      address: "서울특별시 종로구 계동길 37",
      roadAddress: "서울특별시 종로구 계동길 37",
      latitude: 37.582604,
      longitude: 126.983997,
      coordinateStatus: "present",
      estimatedCostKrw: null,
      priceEvidenceSource: null,
      priceEvidenceVerificationStatus: null,
      tourismMetricCount: 4,
      latestTourismPeriod: "2026-07",
      createdAt: "2026-08-01T00:00:00.000Z",
      updatedAt: "2026-08-20T00:00:00.000Z",
    },
    {
      id: "demo-p-3",
      name: "성수 로컬 베이커리",
      source: "naver",
      sourcePlaceId: "nav-3001",
      category: "음식점",
      address: "서울특별시 성동구 연무장길",
      roadAddress: "서울특별시 성동구 연무장길",
      latitude: null,
      longitude: null,
      coordinateStatus: "missing",
      estimatedCostKrw: null,
      priceEvidenceSource: null,
      priceEvidenceVerificationStatus: null,
      tourismMetricCount: 0,
      latestTourismPeriod: null,
      createdAt: "2026-08-15T00:00:00.000Z",
      updatedAt: "2026-08-21T00:00:00.000Z",
    },
  ],
  page: 1,
  pageSize: 20,
  totalItems: 3,
  totalPages: 1,
};

export const DEMO_PLACE_DETAIL: PlaceDetail = {
  ...DEMO_PLACES.items[0],
  rawCategory: "인문(문화/예술/역사) > 역사관광지 > 고궁",
  district: "종로구",
  tourismMetrics: [
    {
      metricType: "tourism_concentration",
      value: 0.88,
      unit: "ratio",
      periodStart: "2026-07-01",
      periodEnd: "2026-07-31",
      sourceName: "한국관광 데이터랩 집중도",
    },
  ],
  priceEvidence: {
    source: "manual",
    verificationStatus: "verified",
    sourceTitle: "DEMO fixture",
    averageCostKrw: 3000,
    disclaimer: "검증용 데모 기준값",
    lastFetchedAt: "2026-08-21T00:00:00.000Z",
  },
  safeMetadata: { source: "kto", originalId: "1001" },
};

export const DEMO_MEMBERS: PageResponse<MemberListItem> = {
  items: [
    {
      id: "demo-member-1",
      displayName: "東京トラベラー",
      email: "traveler@example.jp",
      locale: "ja",
      status: "active",
      savedTripCount: 3,
      latestSavedAt: "2026-08-21T12:30:00.000Z",
      createdAt: "2026-08-10T09:00:00.000Z",
      updatedAt: "2026-08-21T12:30:00.000Z",
    },
  ],
  page: 1,
  pageSize: 20,
  totalItems: 1,
  totalPages: 1,
};

export const DEMO_SYNC_JOBS: SyncJob[] = [
  {
    key: "kto-seoul-poi",
    name: "KTO 서울 관광지 POI 동기화",
    description: "한국관광공사 TourAPI를 통한 서울 전역 관광지·음식점·숙박 POI 메타데이터 동기화",
    schedule: "수동 실행",
    historyStatus: "unavailable",
    lastRunAt: null,
    lastStatus: null,
    mutationEnabled: false,
    mutationDisabledReason: "관리자 인증·권한·감사 로그가 아직 구현되지 않음",
  },
  {
    key: "kto-datalab-concentration",
    name: "한국관광 데이터랩 집중도 동기화",
    description: "한국관광 데이터랩 방문·소비·관광 흐름 데이터셋 정기 Import 및 관광 지표 feature store 적재",
    schedule: "매월 1회 / 수동 실행",
    historyStatus: "available",
    lastRunAt: "2026-08-20T14:30:00.000Z",
    lastStatus: "completed",
    mutationEnabled: false,
    mutationDisabledReason: "관리자 인증·권한·감사 로그가 아직 구현되지 않음",
  },
];

export const DEMO_SYNC_RUNS: PageResponse<SyncRun> = {
  items: [
    {
      id: "demo-sr-1",
      jobKey: "kto-datalab-concentration",
      startedAt: "2026-08-20T14:20:00.000Z",
      completedAt: "2026-08-20T14:30:00.000Z",
      status: "completed",
      message: "파일: seoul_concentration_202607.csv, 적재: 450, 거절: 2",
    },
  ],
  page: 1,
  pageSize: 20,
  totalItems: 1,
  totalPages: 1,
};

export const DEMO_IMPORTS: PageResponse<ImportRunListItem> = {
  items: [
    {
      id: "demo-imp-1",
      datasetKey: "kto-datalab-concentration",
      datasetName: "한국관광 데이터랩 집중도",
      sourceName: "한국관광공사",
      referencePeriod: "2026-07",
      mode: "live",
      status: "completed",
      fileName: "seoul_concentration_202607.csv",
      acceptedCount: 450,
      rejectedCount: 2,
      startedAt: "2026-08-20T14:20:00.000Z",
      completedAt: "2026-08-20T14:30:00.000Z",
    },
  ],
  page: 1,
  pageSize: 20,
  totalItems: 1,
  totalPages: 1,
};

export const DEMO_IMPORT_DETAIL: ImportRunDetail = {
  ...DEMO_IMPORTS.items[0],
  sourceUrl: "https://datalab.visitkorea.or.kr",
  licenseUseCondition: "공공누리 제1유형",
  spatialGranularity: "district",
  temporalGranularity: "monthly",
  checksumPrefix: "a1b2c3d4e5f6",
  rejectionCodeCounts: { UNMATCHED_PLACE_ID: 2 },
  safeMetadata: { importedBy: "admin", format: "csv" },
};

export const DEMO_EVALUATIONS: PageResponse<EvaluationListItem> = {
  items: [
    {
      id: "demo-eval-1",
      createdAt: "2026-08-21T09:15:00.000Z",
      area: "종로구",
      travelDate: "2026-08-22",
      dataMode: "live",
      evidenceStatus: "available",
      candidateCount: 15,
      baselineAlgorithmVersion: "baseline-v1",
      michiAlgorithmVersion: "michi-v1",
    },
  ],
  page: 1,
  pageSize: 20,
  totalItems: 1,
  totalPages: 1,
};

export const DEMO_EVALUATION_DETAIL: EvaluationDetail = {
  ...DEMO_EVALUATIONS.items[0],
  preferenceSnapshot: { area: "종로구", travelDate: "2026-08-22", themes: ["culture", "food"] },
  candidateSnapshotSummary: {
    totalCandidates: 15,
    withTourismConcentration: 12,
    sources: ["kto", "naver"],
  },
  baselineMetrics: {
    averagePreferenceScore: 0.85,
    tourismConcentrationScore: 0.78,
    nonHotspotInclusionRate: 0.15,
    averageTravelDistanceKm: 3.2,
    averageTravelTimeMinutes: 40.0,
    localImpactScore: 0.35,
  },
  michiMetrics: {
    averagePreferenceScore: 0.83,
    tourismConcentrationScore: 0.42,
    nonHotspotInclusionRate: 0.65,
    averageTravelDistanceKm: 3.9,
    averageTravelTimeMinutes: 48.0,
    localImpactScore: 0.72,
  },
  delta: {
    concentrationReduction: 0.36,
    nonHotspotInclusionLift: 0.5,
    preferenceChange: -0.02,
    extraTravelDistanceKm: 0.7,
    extraTravelTimeMinutes: 8.0,
    localImpactLift: 0.37,
  },
  expectedEffect: {
    algorithmVersion: "expected-dispersion-effect-v1",
    claimScope: "recommendation_estimate",
    evidenceStatus: "available",
    concentrationReduction: 0.36,
    nonHotspotInclusionLift: 0.5,
    preferenceChange: -0.02,
    extraTravelDistanceKm: 0.7,
    extraTravelTimeMinutes: 8.0,
    localImpactLift: 0.37,
  },
  dataSources: [{ name: "한국관광 데이터랩", mode: "live" }],
  warnings: ["이동 거리와 시간은 실제 길찾기가 아닌 직선거리·보행속도 기반 추정치입니다."],
  randomSeed: null,
};

export const DEMO_USERS: PageResponse<import("./contracts").AdminUserDetail> = {
  items: [
    {
      id: "demo-u-1",
      email: "owner@michi.local",
      displayName: "Michi 최고관리자",
      role: "owner",
      status: "active",
      authProvider: "password",
      lastLoginAt: "2026-08-23T05:00:00.000Z",
      createdAt: "2026-08-01T00:00:00.000Z",
      createdBy: null,
    },
    {
      id: "demo-u-2",
      email: "admin@michi.local",
      displayName: "운영 관리자",
      role: "admin",
      status: "active",
      authProvider: "password",
      lastLoginAt: "2026-08-23T04:30:00.000Z",
      createdAt: "2026-08-05T00:00:00.000Z",
      createdBy: "demo-u-1",
    },
    {
      id: "demo-u-3",
      email: "operator@michi.local",
      displayName: "데이터 운영자",
      role: "operator",
      status: "active",
      authProvider: "password",
      lastLoginAt: "2026-08-22T10:00:00.000Z",
      createdAt: "2026-08-10T00:00:00.000Z",
      createdBy: "demo-u-2",
    },
    {
      id: "demo-u-4",
      email: "viewer@michi.local",
      displayName: "조회 전용",
      role: "viewer",
      status: "invited",
      authProvider: "password",
      lastLoginAt: null,
      createdAt: "2026-08-20T00:00:00.000Z",
      createdBy: "demo-u-2",
    },
  ],
  page: 1,
  pageSize: 20,
  totalItems: 4,
  totalPages: 1,
};

export const DEMO_AUDIT_LOGS: PageResponse<import("./contracts").AdminAuditLogItem> = {
  items: [
    {
      id: "demo-al-1",
      adminUserId: "demo-u-1",
      adminUserEmail: "owner@michi.local",
      adminUserDisplayName: "Michi 최고관리자",
      action: "admin.user.invite",
      resourceType: "admin_user",
      resourceId: "demo-u-4",
      result: "success",
      requestId: "req-audit-1",
      ipAddress: "127.0.0.1",
      afterData: { email: "viewer@michi.local", role: "viewer" },
      createdAt: "2026-08-23T05:10:00.000Z",
    },
    {
      id: "demo-al-2",
      adminUserId: "demo-u-2",
      adminUserEmail: "admin@michi.local",
      adminUserDisplayName: "운영 관리자",
      action: "admin.login",
      resourceType: "admin_session",
      resourceId: null,
      result: "success",
      requestId: "req-audit-2",
      ipAddress: "127.0.0.1",
      createdAt: "2026-08-23T04:30:00.000Z",
    },
    {
      id: "demo-al-3",
      adminUserId: "demo-u-3",
      adminUserEmail: "operator@michi.local",
      adminUserDisplayName: "데이터 운영자",
      action: "admin.user.invite",
      resourceType: "admin_user",
      resourceId: null,
      result: "denied",
      requestId: "req-audit-3",
      ipAddress: "127.0.0.1",
      createdAt: "2026-08-22T14:20:00.000Z",
    },
  ],
  page: 1,
  pageSize: 20,
  totalItems: 3,
  totalPages: 1,
};
