FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
COPY . ./

ARG NEXT_PUBLIC_ADMIN_API_URL
ARG NEXT_PUBLIC_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_APP_ENV=production
ARG NEXT_PUBLIC_ADMIN_DEMO_MODE=false
ARG NEXT_PUBLIC_ADMIN_AUTH_MODE=session
ENV NEXT_PUBLIC_ADMIN_API_URL=$NEXT_PUBLIC_ADMIN_API_URL \
    NEXT_PUBLIC_PUBLIC_API_URL=$NEXT_PUBLIC_PUBLIC_API_URL \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV \
    NEXT_PUBLIC_ADMIN_DEMO_MODE=$NEXT_PUBLIC_ADMIN_DEMO_MODE \
    NEXT_PUBLIC_ADMIN_AUTH_MODE=$NEXT_PUBLIC_ADMIN_AUTH_MODE
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production PORT=3100 HOSTNAME=0.0.0.0

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

USER node
EXPOSE 3100
CMD ["node", "server.js"]
